apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-demo
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      containers:
      - image: shansongxian/jenkins-demo:<BUILD_TAG>
        imagePullPolicy: Never #test result usage Never
        name: jenkins-demo
        env:
        - name: branch
          value: <BRANCH_NAME>
